INSERT INTO SHOP_MANAGEMENT.PRODUCT (PRODUCT_ID, NAME, DESCRIPTION, PRIZE) VALUES
  (1, 'jabłko LIGOL', 'spożywany na surowo', 0.98),
  (2, 'woda Nałęczowianka', 'kupowana w butelkach 1,5l', 1.50);
    
INSERT INTO SHOP_MANAGEMENT.UNIT_TYPE (UNIT_TYPE_ID, UNIT_NAME) VALUES
  (1, 'KILOGRAM'),
  (2, 'UNIT'),
  (3, 'LITRE');
  
INSERT INTO SHOP_MANAGEMENT.FOOD (PRODUCT_ID, KILOCALORIES_PER_100_GRAMS, UNIT_TYPE_ID) VALUES
  (1, 52.1, 1),
  (2, 0, 3);