CREATE SCHEMA SHOP_MANAGEMENT AUTHORIZATION sa;

CREATE TABLE IF NOT EXISTS SHOP_MANAGEMENT.PRODUCT (
  PRODUCT_ID  LONG PRIMARY KEY,
  NAME		  VARCHAR(50) NOT NULL,
  DESCRIPTION VARCHAR(250),
  PRIZE		  DECIMAL(12,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS SHOP_MANAGEMENT.UNIT_TYPE (
  UNIT_TYPE_ID      LONG PRIMARY KEY,
  UNIT_NAME			VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS SHOP_MANAGEMENT.FOOD (
  PRODUCT_ID 					LONG PRIMARY KEY,
  FOREIGN KEY (PRODUCT_ID)		REFERENCES SHOP_MANAGEMENT.PRODUCT (PRODUCT_ID),
  KILOCALORIES_PER_100_GRAMS	DECIMAL(5,1) NOT NULL,
  UNIT_TYPE_ID 					LONG NOT NULL,
  FOREIGN KEY (UNIT_TYPE_ID)	REFERENCES SHOP_MANAGEMENT.UNIT_TYPE (UNIT_TYPE_ID) 
);