CREATE SCHEMA AITSI AUTHORIZATION sa;

CREATE TABLE IF NOT EXISTS AITSI.PRODUCT_TYPE (
  PRODUCT_TYPE_ID		IDENTITY NOT NULL PRIMARY KEY,
  NAME				    	VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS AITSI.PRODUCT (
  PRODUCT_ID  					        	IDENTITY NOT NULL PRIMARY KEY,
  PRODUCER				  	        		VARCHAR(50) NOT NULL,
  MODEL					    		        	VARCHAR(50) NOT NULL,
  DESCRIPTION 					        	VARCHAR(1000),
  PRIZE		  				  	         	DECIMAL(12,2) NOT NULL,
  PRODUCT_TYPE_ID 					      LONG NOT NULL,
  FOREIGN KEY (PRODUCT_TYPE_ID)		REFERENCES AITSI.PRODUCT_TYPE (PRODUCT_TYPE_ID) 
);

CREATE TABLE IF NOT EXISTS AITSI.PRODUCT_COUNT (
  PRODUCT_ID	              	IDENTITY NOT NULL PRIMARY KEY,
  FOREIGN KEY (PRODUCT_ID)		REFERENCES AITSI.PRODUCT (PRODUCT_ID),
  AVAILABLE_AMOUNT            INTEGER NOT NULL,
  PEOPLE_BOUGHT               INTEGER NOT NULL,
  ITEM_BOUGHT                 INTEGER NOT NULL,
);

