CREATE SCHEMA AITSI AUTHORIZATION sa;

CREATE TABLE IF NOT EXISTS AITSI.PRODUCT_TYPE (
  PRODUCT_TYPE_ID		IDENTITY NOT NULL PRIMARY KEY,
  NAME					VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS AITSI.PRODUCT (
  PRODUCT_ID  						IDENTITY NOT NULL PRIMARY KEY,
  PRODUCER							VARCHAR(50) NOT NULL,
  MODEL								VARCHAR(50) NOT NULL,
  DESCRIPTION 						VARCHAR(1000),
  PRIZE		  						DECIMAL(12,2) NOT NULL,
  PRODUCT_TYPE_ID 					LONG NOT NULL,
  FOREIGN KEY (PRODUCT_TYPE_ID)		REFERENCES AITSI.PRODUCT_TYPE (PRODUCT_TYPE_ID) 
);

